apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.app }}
    spec:
      containers:
      - name: {{ .Values.frontend.app }}
        image: "{{ .Values.frontend.image }}"
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}
        env:
        - name: REACT_APP_BACKEND_URL
          value: "{{ .Values.frontend.backendUrl }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}
spec:
  type: {{ .Values.frontend.serviceType }}
  selector:
    app: {{ .Values.frontend.app }}
  ports:
  - port: {{ .Values.frontend.servicePort }}
    targetPort: {{ .Values.frontend.containerPort }}

